### PR TITLE
Fix #31

### LINKED ISSUE #31: Icomplete-vertical fails with consult-buffer
I get an error:

```
Error in post-command-hook (icomplete-post-command-hook): (args-out-of-range [(:name "Hidden Buffer" :narrow 32 :hidden t :category buffer :face consult-buffer :history buffer-name-history :state consult--buffer-state :items #[0 "\301!\302\303\304\"\305 \"\207" [consult-buffer-filter consult--regexp-filter seq-filter make-closure #[257 "\300\302\303\304#)\207" [V0 inhibit-changing-match-data nil t string-match] 8 "

(fn X)"] consult--cached-buffer-names] 5]) (:name "Buffer" :narrow 98 :category buffer :face consult-buffer :history buffer-name-history :state consult--buffer-state :default t :items #[0 "\301!\302\303\304\"\305 \"\207" [consult-buffer-filter consult--regexp-filter seq-remove make-closure #[257 "\300\302\303\304#)\207" [V0 inhibit-changing-match-data nil t string-match] 8 "

(fn X)"] consult--cached-buffer-names] 5]) (:name "File" :narrow 102 :category file :face consult-file :history file-name-history :action consult--file-action :enabled #[0 "\207" [recentf-mode] 1] :items #[0 "\301 \302\303\304\305\306\"\"\"\207" [recentf-list consult--cached-buffer-file-hash mapcar abbreviate-file-name seq-remove make-closure #[257 "\301\300\"\207" [V0 gethash] 4 "

(fn X)"]] 7]) (:name "Bookmark" :narrow 109 :category bookmark :face consult-bookmark :history bookmark-history :items bookmark-all-names :action consult--bookmark-action)] -1048544)
```

I'm not sure what I'm looking at. Is the first piece of error data the vector of consult-buffer sources? The number `-1048544` looks very wrong.

And it's weird, other functions that use x-group-function seem to work in icomplete-vertical, like `consult-imenu`. And `consult-buffer` still seems to work in Selectrum and Vertico (which is why I filed the bug here and not over an the consult repo).

cc @minad.

### PR DESCRIPTION
**Pull request by minad**
The fix is rather easy thanks to the 'line-prefix

### CODE REVIEW

**Comment by oantolin** [comment]
> The fix is rather easy thanks to the 'line-prefix

Synergy! These packages are ready for the corporate world now.

Thanks for the quick fix! It was silly of me to not group before annotating.

**Comment by minad** [comment]
> Thanks for the quick fix! It was silly of me to not group before annotating.

This was me ;) It wouldn't have worked the other way round before, it only works now like this because of the 'line-prefix.

> Synergy! This package is ready for the corporate world now.

Indeed. But be aware of the evil Emacs Corp. It seems to prepare its own version of an Icomplete-vertical. But with much fewer advices, so clearly inferior to what you have here.

**Comment by oantolin** [comment]
I haven't seen Emacs's version of icomplete-vertical yet, but it seems to be different from what was discussed in the mailing list. For starters, it involves an extra `icomplete-vertical.el` file. I thought we had agreed it was best achieved with a few tweaks to `icomplete.el`, and that it should kick in automatically if the separator contained a newline. 🤷🏽

**Comment by minad** [comment]
Yes, I agree with you. But for example fido-mode should better go to a separate file and have command names like `fido-...`. icomplete.el has become a bit more complex than necessary. But well, I have vertico now which is close enough to default completion/icomplete. Unfortunately 2 lines is not enough to implement [horico-mode](https://github.com/minad/vertico/commit/37710c3ad2ad4b6ef7009a142e75f1a69c34f5d7) :shrug:

**Pull request merged**
