### PR TITLE
Replace x-group-function with x-title-function, add support for candidate transformations

### PR DESCRIPTION
**Pull request by minad**
See long discussion in https://github.com/minad/consult/pull/285, supersedes #34

### CODE REVIEW

**Comment by minad** [comment]
See long discussion in https://github.com/minad/consult/pull/285

**Comment by oantolin** [comment]
This is what's been settled upon to replacing the grouping? To make sure I understand:

- There is a function that given a candidate returns the title of the group it belongs to.
- There is a function that can tweak a candidate for display (I'm guessing removing stuff redundant with the group title, like file names in grep results?).
- For some reason these two functions are squished into a single one that has an argument to request one behavior or the other.
- There is no longer any opportunity for the grouping function to do any sorting, since these functions are always called with one candidate at a time.

Is that right? If so, I think I like it. I certainly won't miss the group sorting at all, it seemed kind of unnecessary. I'm not too crazy about the argument to select between two fairly different behaviors, but I guess it's OK. One could have a unary function that returns `(cons title transformed-candidate)`, but I'm guessing you rejected that because it conses. One could have separate (unary) `title` and `transform` functions but maybe those would need to share some title-determining logic (in the grep results example, they might both search for the first colon, for example) and could benefit from being combined. Also, two functions are probably harder to sneak upstream than one. ;)

Did I more or less understand what's going on?

**Comment by minad** [comment]
Yes, you understood. I am glad you like it. The group sorting was something I liked in the beginning since I wanted the flexibility. However it turned out that I never actually used this group sorting feature in Consult. The new design is simpler and pushes the complexity from the completion table to the completion system, which is good. It is essentially our original title-function only enhanced with the anti-redundancy transformation which I recently added. I did not reject the cons return value because of the cons allocation but because of the significantly more expensive string allocation of the transformed candidate. This is a very good reason to go with the argument. Having two unary functions was also considered but having a single function for a single feature seems better to me and Stefan and Dmitry did not object.

**Comment by minad** [comment]
Anything missing here or is this ready to merge? I hope I can get this feature into upstream too, so you may see one more PR which changes the name again to the name chosen by upstream.

**Comment by oantolin** [comment]
Thanks for doing this!

**Pull request merged**
