### PR TITLE
Rename `x-title-function` to `group-function` as per Emacs 28

### PR DESCRIPTION
**Pull request by minad**
* https://github.com/minad/consult/commit/556ff4eb31eb1d00a2afdda6664d03b698264e3c
* https://github.com/emacs-mirror/emacs/commit/443d9efc9524be6aff5d9703b81a821b3bb12f35

### CODE REVIEW

**Comment by minad** [comment]
Btw, do you also want to have this optimization:

https://github.com/minad/vertico/blob/152f560f28627a9a249929381bbe37c97f220744/vertico.el#L280-L298

or are you happy with the current readable version:

https://github.com/oantolin/icomplete-vertical/blob/d7ab5e5de18a027375666755e6610ea26c35ac16/icomplete-vertical.el#L286-L295

**Comment by oantolin** [comment]
Thanks for doing this!

Also, I'm really happy about the `grouper` variable. This is a grouper: 
image

**Comment by oantolin** [comment]
Ah, I had forgotten that now `consult-ripgrep` groups by file. One could potentially search a hundred files, I guess. I bet for my usage the two versions are probably indistinguishable, but it might be worth using a hashtable for people who grep through many files.

**Comment by oantolin** [comment]
Have you ever observed the hashtable being faster? If so, how many groups did it take for the speed up to be noticeable?

**Comment by oantolin** [comment]
I don't think groups*candidates is the right parameter. For example if groups=1, I bet the alist is faster no matter how many candidates you have. But if you have done profiling to test that the hashtable is faster on reasonably realistic workloads, that's good enough for me.

**Comment by oantolin** [comment]
Is it OK with you if I just take the function from Vertico?

**Comment by minad** [comment]
> I don't think groups*candidates is the right parameter. For example if groups=1, I bet the alist is faster no matter how many candidates you have.

Of course you are right.  The hashtable will be very bad for a small number of groups and a large number of candidates, then the constants matter. The point is that I want a behavior which scales reasonably well. In my tests this is so much more important, since this introduces "hang ups". Larger constants only make things a little bit slower.

> Is it OK with you if I just take the function from Vertico?

Sure, go ahead. The same function is in Selectrum and Vertico.

**Comment by oantolin** [comment]
I am wondering if I should use something a little easier to follow, even if it conses quite a bit more, like this:

```elisp

(defun icomplete-vertical--group-by (fun elems)
  "Group ELEMS by FUN."
  (let ((groups (make-hash-table :test #'equal)) keys)
    (dolist (cand elems)
      (let ((key (funcall fun cand nil)))
        (unless (gethash key groups) (push key keys))
        (push cand (gethash key groups))))
    (mapcan (lambda (key) (nreverse (gethash key groups)))
            (nreverse keys))))
```

**Comment by minad** [comment]
That's also good. I used something like this before (I didn't have groups and keys, I had groups-hash and groups-list, but otherwise the same). The only difference are the allocations. Of course I profiled this.

It won't matter for icomplete-vertical since you are also using the slow `completion-all-sorted-completions`. Vertico also uses an optimized sorting function. For all these reasons I have been hesitant to propose this optimized function to icomplete-vertical.

**Pull request merged**
