### PR TITLE
Expand gitignore to two standard file extensions

### PR DESCRIPTION
**Pull request by protesilaos**
I learnt about these from an ELPA maintainer.  Might be useful in other
packaging scenaria as well.

Again though, feel free to reject or adapt accordingly.

### CODE REVIEW

**Comment by oantolin** [comment]
The package.el machinery creates these automatically, right? Merged, thanks!

**Comment by protesilaos** [comment]
You are welcome! Yes, assuming you get packages this way, you can see such files in each subdirectory inside of `~/.emacs.d/elpa/` (or equivalent).

**Comment by basil-conto** [comment]
Just curious: if these files are only generated under `package-user-dir` upon installing the package, then what is achieved by ignoring them under the source tree of the `icomplete-vertical` project?

Is it to handle the case where a developer of `icomplete-vertical` manually generates these files under the project's source tree, or uses the source tree as a member of `package-directory-list` or similar, i.e. a package installation destination?

**Comment by protesilaos** [comment]
Without such exceptions the ELPA maintainer would be getting feedback on untracked files. I assume the same would apply for any kind of machinery or workflow that mimics ELPA's.

In practice though, this is not of immediate concern to this project and might actually not be useful outside the ELPA context.

Feel free to remove/adapt as needed.

**Comment by basil-conto** [comment]
> Feel free to remove/adapt as needed.

I'm not advocating their removal, just curious when and how these files would be generated under the source tree, since AFAIK the files are only generated when installing a package or packaging it in a tarball.

But I'm not familiar with ELPA tooling, which is why I'm pestering you with all these questions :) (sorry)

> Without such exceptions the ELPA maintainer would be getting feedback on untracked files.

Feedback from what, and after taking which action?

> In practice though, this is not of immediate concern to this project and might actually not be useful outside the ELPA context.

It also does no harm...

**Comment by protesilaos** [comment]
Sorry for the lack of clarity. By "feedback" I meant the `git status`.

As noted in the commit message, these were brought to my attention by an ELPA maintainer, so I thought they might be useful in other/similar packaging scenaria.  Given that their exclusion seems harmless/innocuous, I decided to proceed with this PR.

**Comment by basil-conto** [comment]
I'm not questioning why you decided to submit this PR; I'm just curious to learn under what circumstances these files would appear under the project's source tree.

So far, my first guess:

> Is it to handle the case where a developer of `icomplete-vertical` manually generates these files under the project's source tree

sounds like the most likely scenario.

Thanks for obliging!

**Pull request merged**
