### PR TITLE
Silence linter: `icomplete-vertical-save-values'

### PR DESCRIPTION
**Pull request by protesilaos**
This is just a suggestion to silence the package linter. Feel free to adapt accordingly.

### CODE REVIEW

**Comment by oantolin** [comment]
I need to learn how to use the linter. Is the issue it complains about that the first sentence of a docstring should fit on one line? I can see how that would be good style.

**Comment by basil-conto** [comment]
I haven't used `package-lint`, but keeping the first sentence of docstrings to one line and ideally less than 67 characters wide is a standard Emacs convention; see [`(elisp) Documentation Tips`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Tips.html).

For what it's worth, rather than remembering this and/or counting columns, I've instead developed the habit of typing <kbd>M-q</kbd> (`fill-paragraph`) whenever I'm editing a docstring, which generally does the right thing.

The built-in `checkdoc` package also helps enforce these kinds of conventions.

**Comment by oantolin** [comment]
Thanks @basil-conto! I'll look into both `package-lint` and `checkdoc`.

I do use `M-q` on docstrings, but of course, it doesn't make you keep the first sentence on one line, :)

**Comment by protesilaos** [comment]
Thanks to both! Yes, `M-q` is also what I do after rewording the string.  The `package-lint` part that I use (though you could also try it stand-alone or with `flymake`):

```elisp
(use-package flycheck
  :ensure t
  :commands flycheck-mode
  :config
  (setq flycheck-check-syntax-automatically
        '(save mode-enabled)))

(use-package package-lint
  :ensure t)

(use-package flycheck-package
  :ensure t
  :after (flycheck package-lint)
  :config
  (flycheck-package-setup))
```

**Pull request merged**
